name: build-and-deploy

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Which tag or version will be built'
        default: 'main'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate Docker Image Name
        id: 'docker_image_name'
        env:
          BUILD_TAG: ${{ github.event.inputs.build_tag }}
        run: |
          if [ "${BUILD_TAG}" = "main" ]; then
            docker_tag="latest";
          else
            docker_tag="${BUILD_TAG}"
          fi
          echo "::set-output name=image_name::steemit/nginx-proxy:${docker_tag}"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_image_name.outputs.image_name }}
