name: build-and-deploy

on:
  push:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Which tag or version will be built'
        default: 'main'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Generate Docker Image Name
        shell: bash
        id: 'docker_image_name'
        env:
          CURRENT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          set -x
          if [ "${CURRENT_BRANCH}" = "main" ]; then
            docker_tag="latest";
          else
            docker_tag="${CURRENT_BRANCH}";
          fi
          echo "::set-output name=image_name::steemit/nginx-proxy:${CURRENT_BRANCH}"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_image_name.outputs.image_name }}
